name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker build -t jtvertigo/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true jtvertigo/react-test npm test
